# Generated by Django 4.1.7 on 2023-04-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_nac', models.DateField(default='01/01/1900')),
                ('parentezco', models.TextField(max_length=10)),
            ],
        ),
    ]
