# Generated by Django 4.1.7 on 2023-04-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nac',
            field=models.DateField(default='1989-28-11'),
        ),
    ]
